### ISSUE TITLE
Incorrect site name for Tumblr permalinks

### ISSUE THREAD

**Issue by David-337** [itteco/iframely#215]
When the iframely API is given a Tumblr permalink, the `site` field in `meta` is now showing the blog's name instead of "Tumblr"

example:
`/iframely?url=https://lambdageneration.tumblr.com/post/185796022700/half-life-mini-figures-by-mark-hos-art`

response:

```json
{
    "meta": {
        "canonical": "https://lambdageneration.tumblr.com/post/185796022700/half-life-mini-figures-by-mark-hos-art",
        "site": "LambdaGeneration",
        "author": "LambdaGeneration",
        "author_url": "https://lambdageneration.tumblr.com/",
        "description": "Half-Life mini-figures by Mark-hos Art",
        "title": "lambdageneration",
        "amphtml": "https://lambdageneration.tumblr.com/post/185796022700/half-life-mini-figures-by-mark-hos-art/amp",
        "keywords": "half-life,fan art,models,mini-figures,headcrab",
        "media": "reader"
    },
```

**Comment by iparamonau** [comment]
This is the result of #212. `oembed-site` used to be the highest priority meta, but no longer is due to other requirements. 

If you configure Iframely to use Tumblr API directly, not through generic parsers - then our custom domain plugin will kick in and will provide "Tumblr" as the sitename (as it is in the [cloud](https://iframely.com/embed/https%3A%2F%2Flambdageneration.tumblr.com%2Fpost%2F185796022700%2Fhalf-life-mini-figures-by-mark-hos-art) ).

To configure Tumblr API, see `config.local.js.SAMPLE`,  `.providerOptions.tumblr`
