### ISSUE TITLE
VK videos doesn't seem to work, they do work at the cloud version.

### ISSUE THREAD

**Issue by Yahav** [itteco/iframely#222]
Try this URL:
https://vk.com/video-51189706_456247608

at the Iframely website it does produce the following embed code at the 'html parameter' (https://iframely.com/embed/https%3A%2F%2Fvk.com%2Fvideo-51189706_456247608):
`<div style="left: 0; width: 100%; height: 0; position: relative; padding-bottom: 56.25%;"><iframe src="https://vk.com/video_ext.php?oid=-51189706&id=456247608&hash=8256b948f3f020fd&hd=1" style="border: 0; top: 0; left: 0; width: 100%; height: 100%; position: absolute;" allowfullscreen scrolling="no" allow="encrypted-media"></iframe></div>
`

at the self-hosted version i do get a response but i don't get the 'html' parameter, hence its not embbedable, the debug data i get: https://pastebin.com/ebjKWf2i

**Comment by iparamonau** [comment]
Self-hosted and cloud can differ. It's expected. Please see what can be the difference:
https://github.com/itteco/iframely#not-included-as-compared-to-cloud-api

Now, for VK - they actually don't have the manual copy-paste function for the embed codes. They have had them completely disabled for a bit. At the moment, we consider them unstable. We only keep their codes in the cloud, because we can quickly react to changes and disable if necessary. Self-hosted has a longer release cycle.

**Comment by Yahav** [comment]
I understand.
I think that you should give the developer the option to choose whether or not to include those unstable providers under "use at your own risk" clause.

Simply not providing them at all seems more like a marketing approach although there is no denying that you don't have to provide a self-hosted open source version at all.
i just think that an open source version should offer more freedom of choice for developer.

**Comment by iparamonau** [comment]
Perhaps we owe some better docs. However, as developer, you can have any number of your own plugins. Just configure their folder in `CUSTOM_PLUGINS_PATH` - see example config for (a bit) more.
