### ISSUE TITLE
issue with title in embeds

### ISSUE THREAD

**Issue by eiennohi** [itteco/iframely#230]
If you check the following link: https://themindunleashed.com/2019/11/obama-would-speak-up-to-stop-bernie-sanders.html , the title in the response only says "Obama", which doesn't match the actual title from the article.

Looking at that page's meta tags, you can see it seems to be taking the title from the `twitter:title` tag, instead of `og:title`:
```html
<meta property="og:title" content="Obama &quot;Would Speak Up to Stop&quot; Bernie Sanders From Becoming President in 2020: Report">

<meta name="twitter:title" content="Obama " would="" speak="" up="" to="" stop"="" bernie="" sanders="" from="" becoming="" president="" in="" 2020:="" report"="">
```

Thanks in advance :grin:

**Comment by iparamonau** [comment]
True, Iframely is likely giving a preference to Twitter title - that comes from experience and covers wide variety of sites.

That's not the problem. The problem is caused by the fact that the site has two `twitter:title`s, and one of them isn't html-escaped:

`<meta name="twitter:title" content="Obama " Would Speak Up to Stop" Bernie Sanders From Becoming President in 2020: Report">`

I'd say the issue needs to be fixed on publisher's end

**Comment by eiennohi** [comment]
You're right, thank you!
Hadn't noticed the second `twitter:title` tag.
