### ISSUE TITLE
Is it possible to disable calls to 3rd party systems

### ISSUE THREAD

**Issue by tombburnell** [itteco/iframely#260]
When iframely calls out to youtube/twitter etc. What information is it fetching?

Can this be disabled and just use iframely for the templating?

We don't currently use the metadata returned in the JSON, just the html,  but we are getting 429 failures because we hit youtube so much.

**Comment by iparamonau** [comment]
Iframely checks every URL because it needs to make sure it is available. With YouTube, for example, you'd also want to know the aspect-ratio of the video and whether the video is embeddable at all. 

So we don't do templating. There are plenty of other libraries that give you can try for that or even do it yourself. I imagine it's just a simple (and long) list of regular expressions and a matching  template.

You can use this as inspiration - https://github.com/nfl/jquery-oembed-all. But please be advised that any such library is quite difficult to maintain.

**Comment by tombburnell** [comment]
Our problem is that we are hammering youtube and getting blocked as a
result and they are not very amenable to increasing the quota.
We can cope with the available part ourselves.

Do you guys have a plan more than 1m requests/month?
We\re currently using 200,000 per day

**Comment by iparamonau** [comment]
Our plans do not count the API requests, but rather "hits" - which is a unique URL once per hour. It can be 200'000 requests with that URL in an hour - we'll still count as one hit. 

So our standard pricing is quite accommodating. But if need be, we can discuss more - please ping support at iframely dot com.

However, you guys should still try and configure Iframely's internal cache first to reduce your number of API calls to 3rd parties.

**Comment by tombburnell** [comment]
We can definitely look at that but we're actually caching at about 90%.

What's weird is that we are making approx 10k calls/day to our iframely servers and yet we are seeing 150k queries per day in our google api usage stats.

Any idea why that would be?

We're also seeing "Unspecified" in the google api console. Does iframely make any requests to the API without a key?

**Comment by iparamonau** [comment]
There's only one API request to YouTube, [this one](https://github.com/itteco/iframely/blob/master/plugins/domains/youtube.com/youtube.video.js#L31)

I recommend generating a new API key with google and switching Iframely to it, and seeing if the problem persists.
