### ISSUE TITLE
some youtube urls don't work properly 

### ISSUE THREAD

**Issue by tombburnell** [itteco/iframely#265]
This youtube url seems to fallback to web scraping and doesn't return html in the json

https://www.youtube.com/watch?time_continue=27&amp;v=k3DkuBNymmo

{"type":"link","version":"1.0","title":"YouTube","url":"https://www.youtube.com/","description":"Enjoy the videos and music you love, upload original content, and share it all with friends, family, and the world on YouTube.","thumbnail_url":"https://www.youtube.com/yts/img/yt_1200-vflhSIVnY.png"}

what's happening with it?

**Comment by iparamonau** [comment]
How about decoding html in the URL `&amp;` => `&` ?

**Comment by tombburnell** [comment]
doesn't seem to make any difference

**Comment by tombburnell** [comment]
/oembed?url=https://www.youtube.com/watch?time_continue=27&v=k3DkuBNymmo

**Comment by iparamonau** [comment]
Does this one work as expected?

`/oembed?url=https%3A%2F%2Fwww.youtube.com%2Fwatch%3Ftime_continue%3D27%26v%3Dk3DkuBNymmo`

**Comment by tombburnell** [comment]
Yes, that works. Strange, why does it need url encoding?

this one doesn't
/oembed?url=https://www.youtube.com/watch?v=s-YVawiQc0c

**Comment by iparamonau** [comment]
url encoding is always required. It's just that with your second link you are in luck that it only contains a single `?` and none of `&`s. Otherwise, it will always be ambiguous to where the `&...` part belongs - and it will default to be treated as query-string of the API request itself. 

Anyway, url-encoding is the way to go.

**Comment by tombburnell** [comment]
ok yes makes sense - thanks
