### ISSUE TITLE
iframely : Error write EPIPE (docker install)

### ISSUE THREAD

**Issue by splacat** [itteco/iframely#310]
Not sure if is a bug or a problem of my server but I think is a good idea to open this.
My instance lemmy.cat was no embedding URL images ([see here](https://lemmy.cat/post/100)). I got into iframely docker image and found this error in its log:

Error: write EPIPE
at process.target._send (internal/child_process.js:806:20)
at process.target.send (internal/child_process.js:676:19)
at sendHelper (internal/cluster/utils.js:22:15)
at send (internal/cluster/child.js:190:10)
at EventEmitter.cluster._getServer (internal/cluster/child.js:89:3)
at listenInCluster (net.js:1362:11)
at doListen (net.js:1488:7)
at processTicksAndRejections (internal/process/task_queues.js:81:21)

iframely kept trying restarting but throwing this error again and again. This was the forever processes list:

/iframely # forever list
info: Forever processes running
data: uid command script forever pid id logfile uptime
data: [0] NSkM /usr/local/bin/node cluster.js 18 422 /root/.forever/NSkM.log 0:0:0:46.822

I did a test, I stopped the forever process with forever stopall and started again like this:

forever start -l iframely.log -a server.js

(note that is not cluster.js but server.js what I started.)

...and bingo! iframely started running nicely! and embedding URL images like a charm.

I guess is like a workaround but this solution keep iframely running nicely.

**Comment by iparamonau** [comment]
Hey thanks for reporting. Iframely's Docker is community-maintained. We have no capacity for it ourselves. Feel free to submit the PRs. It will be very much appreciated!

**Comment by marwonline** [comment]
Hey @splacat ,

I know that your issue is already very old, sorry for the late reply.
The latest changes to the docker setup were made by me. Back in https://github.com/itteco/iframely/pull/305 I've removed the `forever` package as docker has a build-in [life-cycle management](https://docs.docker.com/config/containers/start-containers-automatically/). 

Back to your error: 
I could not reprocude it but the error `Error: write EPIPE` ([documentation](https://nodejs.org/api/errors.html)) is an unhandled exception of the network layer inside of NodeJS. The stacktrace points to the cluster implementation, so avoiding the `cluster.js` might help...

One workaround would be using `server.js` directly (as you mentioned) by modifying the [entrypoint.sh](https://github.com/itteco/iframely/blob/master/docker/entrypoint.sh). Personally, I also use this configuration; but keep in mind that this will start a **single NodeJS instance** which will be a bottleneck for massive parallel requests.

**Comment by iparamonau** [comment]
I am closing this because there were a few changes to Docker since. Please open a new issue if there's still a problem
