### ISSUE TITLE
Google embed asks for consent

### ISSUE THREAD

**Issue by hondem** [itteco/iframely#336]
Hello guys. I have an issue with embeding Google Maps. The setup was done according to the tutorial. Without an API key, I was unable to embed YouTube and Google. After creating an API key with YouTube API enabled, YouTube embedding started working. Unfortunately cannot say the same for Google Maps. I've added Maps Embed API to this key but didn't help. I saw that there was exactly the same issue with YouTube in a different issue (https://github.com/itteco/iframely/issues/326) so I was wondering whether somebody already faced the same with maps?

## Request
`http://localhost:8061/iframely?url=https://www.google.com/maps/@49.194908,16.6078658,15.86z`

## Console output
```
-- [21-07-20 14:01:39]:48372 Whitelist activated. Domains, including blacklisted: 1706
-- [21-07-20 14:01:43]:48372 127.0.0.1 - Loading /iframely for https://www.google.com/maps/@49.194908,16.6078658,15.86z
-- [21-07-20 14:01:45]:48372    -- plugin redirect (by "htmlparser") https://consent.google.com/ml?continue=https://www.google.com/maps/@49.194908,16.6078658,15.86z&gl=CZ&m=0&pc=m&hl=cs&src=1
```

## Response
```
{
   "meta":{
      "title":"Before you continue to Google Maps",
      "canonical":"https://consent.google.com/ml?continue=https://www.google.com/maps/@49.194908,16.6078658,15.86z&gl=CZ&m=0&pc=m&hl=cs&src=1"
   },
   "links":{
      "icon":[
         {
            "href":"https://www.google.com/favicon.ico",
            "rel":[
               "shortcut",
               "icon",
               "ssl"
            ],
            "type":"image/icon"
         }
      ]
   },
   "rel":[
      
   ]
}
```

## Location
- Europe

**Comment by iparamonau** [comment]
You probably need EU server to reproduce this error. 

The error is due to `*` mixin requires HTML parser:
https://github.com/itteco/iframely/blob/master/plugins/domains/google.com/google.maps.js#L48

Please try commenting out this line and see if the error is gone. 

If it is gone, then the only way for you would be to keep this line commented. Unfortunately, you'll loose meta such as title and description. But the good news is that thumbnail should still be available if you have Static Maps API enabled on your key.

Alternatively, you may try and route Google Maps via non-EU server.

**Comment by hondem** [comment]
The fix worked! Thank you! :)
