### ISSUE TITLE
417 Expectation failed on datawrapper embeds

### ISSUE THREAD

**Issue by komarserjio** [itteco/iframely#347]
Hi Iframely,

We (we are Enterpise API clients) experience issues with embedding datawrapper (https://datawrapper.dwcdn.net) embeds through Iframely API.
Sometimes API responds with the 417 error code:

Request: http://iframe.ly/api/oembed?url=https://datawrapper.dwcdn.net/62F8x/&api_key=XYZ
```json
{
    "status": 417,
    "error": "This looks like JS app with no prerender. If you are the owner, please run templates on the server for <a href=\"https://iframely.com/docs/about\">Iframely robot</a>."
}
```

Same result when trying to Iframely's Check URL page:

![Screenshot 2021-12-03 at 11 55 45](https://user-images.githubusercontent.com/297514/144602489-be70a858-c0b6-47c9-a324-ddc7a7145e4e.png)

It happens randomly with various datawrapper embeds, I can't see any patterns yet. Usually, we solve this by adding random query params to a datawrapper url, but it would be great to have a proper fix for the problem.

Thank you.

Let me know if you need any additional information about our requests.

**Comment by iparamonau** [comment]
Thanks. I also see your request to support. We noticed that problem on Datawrapper's end couple days ago and have just pushed a possible fix out of our pipeline. We'll need to observe it - I will reach out via email. 

I am going to close this issue here, as cloud support isn't part of the open source repo.
