### ISSUE TITLE
Twitter embeds cut off at the bottom

### ISSUE THREAD

**Issue by skyl** [itteco/iframely#364]
Tweets cut off at bottom sometimes: https://free2z.com/pin

I'm essentially using this verbatim: https://iframely.com/docs/react

Is there something I can do with the container div that could make the embeds behave correctly?

Thanks for the awesome project! I'm going to start paying once I get a few wrinkles ironed out! https://free2z.com/iframely

**Comment by iparamonau** [comment]
You're missing our embed.js script on the page. We've added [a section](https://iframely.com/docs/react#add-embed-js-script) to the doc so that this step is more obvious.

I'll close this ticket for now, as we only handle open-source related tickets here. Please follow up to support at iframely.com if you need further assistance.

**Comment by skyl** [comment]
Awesome, thanks! this is exactly what I needed. Glad I asked. One of the links is misformated in the docs BTW `https://iframely.com/docs/(/docs/omit-script#iframely-omits-embed-js-itself)`
