### ISSUE TITLE
Spotify Video podcast do not have the right aspect ratio

### ISSUE THREAD

**Issue by ecamacho** [itteco/iframely#404]
Hi!

I work at Spotify and we recently released support for Video podcasts in our platform and in our embeds endpoints. We're currently investigating this issue: When you use _iframely_ to embed an episode, the video player does not have the right aspect ratio. You can check that using this example: https://iframely.com/embed/https%3A%2F%2Fopen.spotify.com%2Fepisode%2F2jAYGAbZHxReyhtK6kI5xG

Can you help us troubleshooting it? We're happy to collaborate on this as well if you guide us.

**Comment by iparamonau** [comment]
Thanks for the heads-up! This should now be resolved. 

As you can see it in the fix, it's done with a not particularly nice check:

`var isVideo = !!iframe.width; // 100% width for audio episodes is not set in iframe`

Perhaps, you guys could switch video episodes to oembed type video instead of a "rich" one? If you do, please shoot an email to support at iframey dot com so we update it too. It's would be great to have a direct email channel anyway for quicker issues turnaround.
