### ISSUE TITLE
Facebook public posts redirect to facebook.com/login

### ISSUE THREAD

**Issue by shadysamir** [itteco/iframely#422]
Our Facebook config has the access token value properly provided. So many public posts can't be embedded with the following log entry:
```
-- plugin redirect (by "htmlparser") https://www.facebook.com/login/?next=<post url>
```
Other Facebook content, for example videos, are embedded with no issues. Instagram public posts also are embedded with no issue. Our facebook app has all the required settings (hence other content is being parsed).

What I noticed is that the URL is constructed in a new way that I haven't seen before.
```
https://www.facebook.com/<user-slug>/posts/<long-hash>
```
But even with that new pattern, it gets parsed when tested on iframely website.
We're running iframely 2.2.0

**Comment by iparamonau** [comment]
Is there a test URL for this?

**Comment by shadysamir** [comment]
This url
```
https://www.facebook.com/lamlamgouda/posts/pfbid0qsQbo2vzuKgBogPe3CyaRT5FvyDze7Cpn7z6mWAW7RiZDCvpGuBhjFJY2J6kw64vl
```
Generates this log:
```
|iframely  | -- [22-06-23 22:43:44]:14623 127.0.0.1 - Loading /oembed for https://www.facebook.com/lamlamgouda/posts/pfbid0qsQbo2vzuKgBogPe3CyaRT5FvyDze7Cpn7z6mWAW7RiZDCvpGuBhjFJY2J6kw64vl
0|iframely  | -- [22-06-23 22:43:44]:14623    -- plugin redirect (by "htmlparser") https://www.facebook.com/login/?next=https%3A%2F%2Fwww.facebook.com%2Flamlamgouda%2Fposts%2Fpfbid0qsQbo2vzuKgBogPe3CyaRT5FvyDze7Cpn7z6mWAW7RiZDCvpGuBhjFJY2J6kw64vl
```
But it passes in [url debugger](http://debug.iframely.com/?uri=https%3A%2F%2Fwww.facebook.com%2Flamlamgouda%2Fposts%2Fpfbid0qsQbo2vzuKgBogPe3CyaRT5FvyDze7Cpn7z6mWAW7RiZDCvpGuBhjFJY2J6kw64vl)

**Comment by iparamonau** [comment]
Indeed, our public code expects numeric post ID. If we allow `pfbid....`, then Facebook gives us this:

```
-- [22-06-23 23:42:04]:30716 Facebook oembed api - error getting oembed for https://www.facebook.com/lamlamgouda/posts/pfbid0qsQbo2vzuKgBogPe3CyaRT5FvyDze7Cpn7z6mWAW7RiZDCvpGuBhjFJY2J6kw64vl {"message":"(#100) Invalid parameter","type":"OAuthException","code":100,"fbtrace_id":"AWa2ng9Bzj0TN_h3vzGfX0r"} 
```

In other words, Facebook does not support such IDs either. 

Now, the cloud handles that URLs by doing an internal processing redirect to 
`https://www.facebook.com/lamlamgouda/posts/10159814106615664`

Our debugger gets the canonical URL is in the `<meta>` section of your original URL. But unfortunately it seems your server won't get that canonical anyway because it gets treated to a login page by Facebook. Our debugging server does get proper, likely because of the reverse DNS lookup verification.

So it appears that you won't be able to support those new URLs at the moment. Let's hope Facebook adds their support to their Graph API soon.

**Comment by shadysamir** [comment]
The message `{"message":"(#100) Invalid parameter"}` response is what I get even with Facebook's own API testing tool. It's so frustrating. Thanks for the response. I think I need to find a solution with Facebook.
