### ISSUE TITLE
New Tumblr embeds

### ISSUE THREAD

**Issue by essential-randomness** [itteco/iframely#470]
Hello!
It seems like Tumblr has added a new URL pattern for its posts (starting with `at.tumblr.com`). I can correctly get data for posts with that pattern using your own debugger ([see here](https://iframely.com/try?url=https%3A%2F%2Fat.tumblr.com%2Fessential-randomness%2Fyuumei-art-void-cat-but-space-with-moon-for%2Fkmnmdo1nqj5c)), but does not work when used with this code, neither in the `main` nor in the `develop` branch.

Is there some configuration I'm missing, or is there some secret new tumblr config that hasn't trickled down to here yet?

Thank you for the excellent library!

**Comment by essential-randomness** [comment]
For people looking for a fix, you can copy this custom plugin I developed: https://github.com/itteco/iframely/compare/master...essential-randomness:iframely:tumblr-at-final

**Comment by iparamonau** [comment]
Thanks, and apologies for not paying attention.  The Tumblr's URL shortener correctly redirects our cloud to the proper location, no need for that plugin.  I feel that you might try playing with the proxy configuration  as in `PROXY:[...]` and add for example `curl` as the user agent for app.link domain, and you'll get a proper redirect too. 

In fact, I checked our config, and indeed we use Chrome UA as otherwise we get a in-app link redirects:

```
{
            re: [
                /^https?:\/\/(?:[^\/]+\.)?app\.link/i,
            ],
            user_agent: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36'
        }
```

If you're going to keep your plugin, please make sure you `return cb(null);`  instead of simply `return null;`. I realize you have it just in case, but `cb` needs to be called even in that case too.
