### ISSUE TITLE
Google Maps not working

### ISSUE THREAD

**Issue by frumania** [itteco/iframely#61]
Hi,

i am not 100% sure, but it seems like the google map service changed its URL pattern.

E.g. i cannot parse / use iframely correctly with

https://www.google.de/maps/place/London,+Gro%C3%9Fbritannien+und+Nordirland/@51.5286416,-0.1015987,11z/data=!3m1!4b1!4m2!3m1!1s0x47d8a00baf21de75:0x52963a5addd52a99?hl=de

Any idea ?

**Comment by iparamonau** [comment]
It is fixed in the `develop` branch, if you want to pull  from there. 

Here's it is in action:
http://iframely.com/debug?uri=https%3A%2F%2Fwww.google.de%2Fmaps%2Fplace%2FLondon%2C%2BGro%25C3%259Fbritannien%2Bund%2BNordirland%2F%4051.5286416%2C-0.1015987%2C11z%2Fdata%3D!3m1!4b1!4m2!3m1!1s0x47d8a00baf21de75%3A0x52963a5addd52a99%3Fhl%3Dde

If just need a direct fix, you can get [this domain plugin](https://github.com/itteco/iframely/blob/develop/plugins/domains/google.com/google.maps.js) and put it in your plugins folder. 

The URLs aren't new at all. The problem with Google Maps was that for some weird reason for a year they were re-directing our user-agent for all new URLs to the old ones. And so it didn't make any sense for us to write a new parser for them.

**Comment by iparamonau** [comment]
Oh, I should have mentioned - Google Maps now require maps API key. See sample local config file until we put it in the docs

**Comment by frumania** [comment]
Thanks!

Yeah, i saw that :). Working on it.
